---
version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    open-pull-requests-limit: 0 # security updates only
    schedule:
      interval: "monthly"
    versioning-strategy: "increase"
