name: "CI"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "./.github/actions/poetry"
        with:
          save-cache: "true"
      - run: "./bin/dev.sh lint"
      - run: "./bin/dev.sh typecheck"

  test:
    runs-on: "ubuntu-latest"
    needs:
      - "lint"
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "./.github/actions/poetry"
        with:
          python-version: "${{ matrix.python-version }}"
      - run: "./bin/dev.sh test:cover"

  build:
    runs-on: "ubuntu-latest"
    needs:
      - "test"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "./.github/actions/poetry"
      - run: "poetry build"
      - uses: "actions/upload-artifact@v4"
        with:
          if-no-files-found: "error"
          path: "dist/*"
          name: "dist"

  docs:
    runs-on: "ubuntu-latest"
    needs:
      - "test"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "./.github/actions/poetry"
        with:
          extra-groups: "docs"
      - run: "./bin/dev.sh docs"
      - uses: "actions/upload-artifact@v4"
        with:
          if-no-files-found: "error"
          name: "docs"
          path: "docs/build/**"
